name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  audioplayers: ^6.0.0
  auto_route: ^8.1.4
  auto_route_generator: ^8.1.0
  cloud_firestore: ^5.1.0
  connectivity_plus: ^6.0.4
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_date_pickers: ^0.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  loader_overlay: ^4.0.1
  lottie: ^3.1.2
  intl: any
  pie_chart: ^5.4.0
  rename_app: ^1.6.1
  textfield_tags: ^3.0.1
  l10n_flutter: ^1.0.7
  android_alarm_manager_plus: ^4.0.4
  android_alarm_manager: ^2.0.2
  alarm: ^3.1.5
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/welcome_banner.svg
   - assets/images/profile_image.png
   - assets/icons/back_ic.svg
   - assets/images/mobile_number_banner.svg
   - assets/images/empty_img.svg
   - assets/images/Signing document.gif
   - assets/done.mp3
   - assets/lottie/Animation - 1722508581590.json
flutter_intl:
  enabled: true